### PR TITLE
Add Github Actions configureation

### PR DESCRIPTION
**Pull request by szabgab**

### CODE REVIEW

**Comment by ology** [comment]
So, I'm not actually interested in my non-mission-critical, "just for fun", Perl modules CI'd. This includes all my music ones.

**Comment by szabgab** [comment]
ok, though I don't understand why? and what is the cost to you for having CI enabled?

**Comment by ology** [comment]
Time spent merging CI code to my 50-or-so non-critical CPAN repos?

**Comment by szabgab** [comment]
ok, then I won't spend time creating them.

**Pull request closed without merging**
